### PR TITLE
Replace ReactDOM.findDOMNode with React.createRef

### PR DESCRIPTION
**Pull request by Ginioo**
Hi,

This PR is trying to solve this issue: https://github.com/STRML/react-grid-layout/issues/1091

### CODE REVIEW

**Comment by Ginioo** [comment]
Hi @n1ghtmare,

Good day.

Which minor version bump would be a right fit for this PR?

**Comment by darekkay** [comment]
I think @n1ghtmare meant the version bump for `react-grid-layout`, i.e., the next release should be `0.18.0` instead of `0.17.1`. This is already required due to https://github.com/STRML/react-grid-layout/pull/1060

**Comment by n1ghtmare** [comment]
Yep, thanks @darekkay, that's exactly what I meant.

**Comment by eric-burel** [comment]
`findDOMNode` can create issues when using  `npm link` to develop, maybe this update could fix that to?

**Comment by STRML** [comment]
Thanks, this looks good. However you should not increment the version in a PR. I will edit and merge.

**Comment by STRML** [comment]
[Refs are created using React.createRef() and attached to React elements via the ref attribute.](https://reactjs.org/docs/refs-and-the-dom.html#creating-refs)

You are not actually attaching the ref at `this.currentNode`.

The tests as written are not complete, I still have not gotten around to using Enzyme to actually mount RGL and manipulate grid items / validate callbacks and layouts. Therefore the actual attached tests are quite limited and would not catch that this ref is not attached. Try instead to run the dev layout using `yarn dev`.

**Comment by angus-88** [comment]
any update on when this might be merged?

**Comment by STRML** [comment]
When it is complete.

**Comment by redblue9771** [comment]
Does anyone deal with this PR？

**Comment by dantman** [comment]
Relevant: STRML/react-draggable#478

For this PR to be complete it needs `nodeProp={this.currentNode}` to be passed to `<DraggableCore ...`.

**Comment by hdsantos89** [comment]
any updates when it might be resolved? thanks!

**Comment by eric-burel** [comment]
I am updating an old project where I need refs, I might take a look by the end of summer (but not sure yet)

**Comment by ben-elsen** [comment]
Are there any updates about this issue/PR?

**Comment by RohanKapurDEV** [comment]
Any ETA on this? It's not too disruptive so it's not particularly urgent but it is rather annoying to deal with. Is there any way I can help speed this up? Let me know what I can do.

**Comment by idMolotov** [comment]
@STRML @n1ghtmare Hi!

Just wondering :) How about to merge this PR ? :)

**Comment by Ginioo** [comment]
Hi @STRML,

Could you please review this PR again.
Bear with me, I'm not familiar with typescript...

**Comment by STRML** [comment]
Merged in #1425, thanks @Ginioo!

**Pull request closed without merging**
