### PR TITLE
WIP: Multiple React Grid Layout Drag and Drop

### PR DESCRIPTION
**Pull request by hiddensanctum**
Peek 2021-04-26 12-17

## What has been done
- Added a new `isDetachable` prop that will dictate whether or not you are able to detach a block from a RGL and add it to another RGL.
- A bunch of development `console.log`
- Example 19 to test out dragging between sections

## What still needs to be done
- Drag API that will allow you to access the layout of the block being dragged
- Update example to have a container state that keeps track of the layouts + blocks of each RGL
- Update example so that the block being dragged from one RGL to another will be removed from the original and added to the new RGL
- Add tests to make sure the existing functionality of RGL is not impacted
- Make sure existing drag within section functionality is still working
- Clean up any development logs

## How to develop
- Ask me to add you to the repo so you can edit
- Run `npm run view-example` to load the development server
- Navigate to example 19
- Make changes and things will auto rebuild

### CODE REVIEW

**Comment by elodszopos** [comment]
Hey @hiddensanctum - any progress made since last updates? I'd be interested in what's being added here.

**Comment by hiddensanctum** [comment]
> Hey @hiddensanctum - any progress made since last updates? I'd be interested in what's being added here.

No new updates. The work on this has been paused for the time being.

**Comment by jeremyjohn** [comment]
Looking forward to this.

**Comment by sommoMicc** [comment]
@STRML have you planned to integrate this feature?

**Comment by viralshah-15** [comment]
@hiddensanctum, Any Updates on this feature? any possibilities from your end to make this feature stable?  Thanks.

**Comment by hiddensanctum** [comment]
> Why u just close this PR?

Work on this has completely stopped. It is also way too far from the `master` branch at this point

**Comment by lidorbt-esggo** [comment]
Why did you close it?
this is a very useful feature.

**Pull request closed without merging**
