### PR TITLE
deeply clone the layout into oldLayout to ensure when we compare the …

### LINKED ISSUE #1606: When using allowOverlap prop the onLayoutsChanged event is not fired when dragging of an item ends
Issue: When using allowOverlap prop the onLayoutsChanged event is not fired onDragStop. 

I have made a sandbox showing the issue. Watch the counters above the grid and move the items to see the issue when items are dragged. This is not affecting resizing of items.

- Expected behaviour: 
- Each time and item is dragged: 
-      onDragStop counter increases by 1 ✅
-      onLayoutChanged counter increases by 1 ❌
-      onResizeStop Counter remains the same ✅
-   Each time an item is resized: 
-      onResizeStop counter is increased by 1 ✅
-      onLayoutChanged counter is increased by 1 ✅
-      onDragStop counter remains the same ✅

Example of issue: https://rb7fq.csb.app/
Sandbox of issue: https://codesandbox.io/s/exciting-brahmagupta-rb7fq

### PR DESCRIPTION
**Pull request by woollsta**
…oldLayout it correctly detects it as changed (fixes #1606)

Thanks for submitting a pull request to RGL!

Please reference an open issue. If one has not been created, please create one along with a failing
example or test case.

Please do not commit built files (`/dist`) to pull requests. They are built only at release.

### CODE REVIEW

**Comment by STRML** [comment]
What issue does this solve? And why not use the `cloneLayout` helper which is much faster and doesn't require a dependency?

**Comment by STRML** [comment]
Ah I see. The layout is directly mutated when `allowOverlap` is present in #1619.

**Comment by woollsta** [comment]
Thanks, good spot, I'm not too familar with your project. Using the cloneLayout now and still working.

**Comment by STRML** [comment]
Fixed in #1620, thanks for bringing this to my attention.

**Pull request closed without merging**
