### PR TITLE
Fix Npm build - remove coverage folder (-60%size) - move eslint parser to devDependencies

### PR DESCRIPTION
**Pull request by salvoravida**
Hi guys,
First of all, I have to say thank you for this great library!

This PR fixes two small bugs on the Npm build side:
- remove coverage folder (-60%size) 
- move "@babel/eslint-parser" to devDependencies.

Regards!

### CODE REVIEW

**Comment by salvoravida** [comment]
fyi: https://www.unpkg.com/browse/react-grid-layout@1.3.2/coverage/

**Comment by STRML** [comment]
Thanks! These are bugs for sure so I'll do a point release to get this out ASAP and save some bytes.

**Comment by STRML** [comment]
Thanks. Published in `1.3.3`. Solid fix:

Before:
```
npm notice package size:  245.6 kB
npm notice unpacked size: 1.2 MB
```

After:
```
npm notice package size:  131.1 kB
npm notice unpacked size: 487.7 kB
```

**Comment by salvoravida** [comment]
it also fixes a warning:
warning "react-grid-layout > @babel/eslint-parser@7.16.5" has unmet peer dependency "@babel/core@>=7.11.0".

great!

**Pull request merged**
