### PR TITLE
(#889) change breakpoint/layout event order

### PR DESCRIPTION
**Pull request by EliMiX**
fix: #889 

In Responsive, the onBreakpointChange event occurs after the
onLayoutChange event. So if the onLayoutChange event is used to save
the layout based upon the current breakpoint, the save will overwrite
the previous layout becuase the breakpoint you would be updating will
be the previous layout before changing breakpoints.

This PR will swap the order to onBreakpointChange -> onLayoutChange

### CODE REVIEW

**Comment by Piturzasty** [comment]
Any updates on merging this?

**Comment by stevearoonie** [comment]
I too am very keen on seeing this merged

**Comment by smeevil** [comment]
Any blocking issues for this that prevent the merge? It would solve the problems I currently have as well :)

**Comment by vovsemenv** [comment]
Any update?

**Comment by STRML** [comment]
Thanks!

**Comment by vovsemenv** [comment]
will release soon?

**Pull request merged**
